### ISSUE TITLE
Fails on large files

### ISSUE THREAD

**Issue by golsby** [mcneel/lassie#2]
lassie mcneel/rhino build/bin/NuGet.exe de368517d39ea24ce139de5c3e3b52b884c63f3f NuGet.exe

**Comment by pearswj** [comment]
Ah, I think I know why this is. The API I'm calling only returns the
content for files under 1MB. I figured we'd only be fetching source files
so I didn't bother handling the case where the file is larger than 1MB.
I'll get it done!
